name: TFLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.11.2

    - name: Terraform init
      run: terraform init

    - name: Check Terraform formatting
      run: terraform fmt -check -recursive

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Run TFLint Init
      run: tflint --init

    - name: Run TFLint
      run: tflint

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov
      run: checkov -d . --skip-check CKV2_GHA_1 --skip-check CKV_GCP_69 --skip-check CKV_GCP_61 --skip-check CKV_GCP_13 --skip-check CKV_GCP_65 --skip-check CKV_GCP_66 --skip-check CKV_GCP_12 --skip-check CKV_GCP_123 --skip-check CKV_GCP_23 
